### ISSUE TITLE
Covid-drdb, if a study only contains fold change data, the table will be blank.

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb#13] opened 2021-11-10 22:01 UTC
Please see this link: https://covdb.stanford.edu/search-drdb/?article=Margolis21&host=human

**Comment by philiptzou** [comment] 2021-11-12 20:32
Issue is transferred from hivdb/chiro-frontend after determined the reason was caused by a table-deriving script.

**Closed as completed** 2021-11-13 00:06 UTC
